name: tttplots-update

on:
  workflow_dispatch:
  workflow_run:
    workflows: [tttplots-deploy]
    types:
      - completed
  
jobs:
  update-plots:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_dispatch }}
    name: Python ${{ matrix.python-version }} @ ${{ matrix.os }}.${{ matrix.arch }} (${{ github.event_name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.10'
            os: ubuntu-latest
            arch: x64
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install `tttplots`
      run: >
        python3 -m pip install .
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
      # run: >
      #   git config --global user.name "GitHub Actions";
      #   git config --global user.email "suporte@psr-inc.com";
      #   git add --ignore-errors -f
      #   ./benchmark/results.*;
      #   ./benchmark/toqubo.*;
      #   git commit -m "Save Benchmark Plots [actions]";
      #   git push;